drop policy if exists workspace_members_read on public.workspace_members;
drop policy if exists workspace_read on public.workspaces;
drop policy if exists workspace_update on public.workspaces;
drop policy if exists agents_all on public.agents;
drop policy if exists leads_all on public.leads;
drop policy if exists campaigns_all on public.campaigns;
drop policy if exists campaign_leads_all on public.campaign_leads;
drop policy if exists calls_all on public.calls;
drop policy if exists follow_ups_all on public.follow_ups;
drop policy if exists lead_activities_all on public.lead_activities;
create or replace function private.is_workspace_member(target_workspace uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.workspace_members wm where wm.workspace_id = target_workspace and wm.user_id = auth.uid()); $$;
revoke all on function private.is_workspace_member(uuid) from public, anon, authenticated;
grant execute on function private.is_workspace_member(uuid) to authenticated;
drop function public.is_workspace_member(uuid);
create policy workspace_members_read on public.workspace_members for select using (user_id = auth.uid() or private.is_workspace_member(workspace_id));
create policy workspace_read on public.workspaces for select using (private.is_workspace_member(id));
create policy workspace_update on public.workspaces for update using (exists (select 1 from public.workspace_members wm where wm.workspace_id = id and wm.user_id = auth.uid() and wm.role in ('owner','admin')));
create policy agents_all on public.agents for all using (private.is_workspace_member(workspace_id)) with check (private.is_workspace_member(workspace_id));
create policy leads_all on public.leads for all using (private.is_workspace_member(workspace_id)) with check (private.is_workspace_member(workspace_id));
create policy campaigns_all on public.campaigns for all using (private.is_workspace_member(workspace_id)) with check (private.is_workspace_member(workspace_id));
create policy campaign_leads_all on public.campaign_leads for all using (exists (select 1 from public.campaigns c where c.id = campaign_id and private.is_workspace_member(c.workspace_id))) with check (exists (select 1 from public.campaigns c where c.id = campaign_id and private.is_workspace_member(c.workspace_id)));
create policy calls_all on public.calls for all using (private.is_workspace_member(workspace_id)) with check (private.is_workspace_member(workspace_id));
create policy follow_ups_all on public.follow_ups for all using (private.is_workspace_member(workspace_id)) with check (private.is_workspace_member(workspace_id));
create policy lead_activities_all on public.lead_activities for all using (private.is_workspace_member(workspace_id)) with check (private.is_workspace_member(workspace_id));
